title = "RustifyWLED Configuration"

[app]
callback_url = "my-rustify-wled-device.local"
#client_id = ""
#client_secret = ""
#idle_image_url = ""

[spotify]
polling_seconds = 2

# Number of albums to precache, if not specified, precaching is disabled
precache_albums = 2

[animation]
target_fps = 30

[target]
host = "my-wled-device.local"
size = [32, 32]