title = "RustifyWLED Configuration"

[app]
callback_url = "my-rustify-wled-device.local"
#client_id = ""
#client_secret = ""
#idle_image_url = ""

[spotify]
polling_seconds = 2

# Number of albums to precache, if not specified, precaching is disabled
precache_albums = 2

[target]
[[target.2d]]
host = "wled-two-dim.local"
size = [32, 32]

[[target.1d]]
host = "wled-one-dim.local"
size = [20, 0]

[animation]
target_fps = 30
